export const SEARCH_REQUESTED = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const UPDATE_QUERY_STRING = 'UPDATE_QUERY_STRING';